package pokemongame;


import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PAWITRA
 */
public class PokemonFrame extends javax.swing.JFrame {
    ArrayList<Pokemon> pokemons = new ArrayList<Pokemon>();
    
    public PokemonFrame() {
       pokemons.add(new Bulbasaur());
       pokemons.add(new Pikachu());
       pokemons.add(new Gyarados());
       pokemons.add(new Bulbasaur());
       pokemons.add(new Pikachu());
       pokemons.add(new Gyarados());
       initComponents();
    }

    /**
     * Creates new form PokemonFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static String printStatus(ArrayList<Pokemon> pokemons,int numPokemon){
        String profile = "Pokemon: " + pokemons.get(numPokemon).getName() + "\nHealth: " + String.format("%.0f", pokemons.get(numPokemon).getHealth()) 
                +"/"+String.format("%.0f",pokemons.get(numPokemon).maxHealth) + "\nWeight: " + String.format("%.02f",pokemons.get(numPokemon).getWeight());
        return profile;
    }
    
    public static String printHealth(ArrayList<Pokemon> pokemons,int numPokemon){
        String statusHealth = "Health: " + String.format("%.0f", pokemons.get(numPokemon).getHealth()) 
                +"/"+String.format("%.0f",pokemons.get(numPokemon).maxHealth);
        return statusHealth;
    }
    
    public static String printWeight(ArrayList<Pokemon> pokemons,int numPokemon){
        String statusWeight = "Health: " + String.format("%.0f", pokemons.get(numPokemon).getHealth()) 
                +"/"+String.format("%.0f",pokemons.get(numPokemon).maxHealth) + "\nWeight: " + String.format("%.02f", pokemons.get(numPokemon).getWeight());
        return statusWeight;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStatus1 = new javax.swing.JTextArea();
        status2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStatus2 = new javax.swing.JTextArea();
        jbFeed = new javax.swing.JButton();
        jbExercise = new javax.swing.JButton();
        jbBattle = new javax.swing.JButton();
        nameBlueTeam = new javax.swing.JComboBox<>();
        nameRedTeam = new javax.swing.JComboBox<>();
        type2 = new javax.swing.JLabel();
        type3 = new javax.swing.JLabel();
        jbChoose = new javax.swing.JButton();
        jcTypeBerry = new javax.swing.JComboBox<>();
        jcTeam = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtExplain = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameProgram = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        blueTeam = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        redTeam = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokemonGame v1.0.1");
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        status1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        status1.setText("Status: Blue Team");
        getContentPane().add(status1);
        status1.setBounds(140, 320, 150, 50);

        txtStatus1.setColumns(20);
        txtStatus1.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        txtStatus1.setRows(5);
        jScrollPane1.setViewportView(txtStatus1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 370, 220, 100);

        status2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        status2.setText("Status: Red Team");
        getContentPane().add(status2);
        status2.setBounds(480, 320, 150, 50);

        txtStatus2.setColumns(20);
        txtStatus2.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        txtStatus2.setRows(5);
        jScrollPane2.setViewportView(txtStatus2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 370, 220, 100);

        jbFeed.setText("Feed");
        jbFeed.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbFeedMouseMoved(evt);
            }
        });
        jbFeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbFeedMouseExited(evt);
            }
        });
        jbFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFeedActionPerformed(evt);
            }
        });
        getContentPane().add(jbFeed);
        jbFeed.setBounds(290, 500, 120, 60);

        jbExercise.setText("Exercise");
        jbExercise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbExerciseMouseMoved(evt);
            }
        });
        jbExercise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbExerciseMouseExited(evt);
            }
        });
        jbExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExerciseActionPerformed(evt);
            }
        });
        getContentPane().add(jbExercise);
        jbExercise.setBounds(130, 500, 120, 60);

        jbBattle.setText("Battle");
        jbBattle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbBattleMouseMoved(evt);
            }
        });
        jbBattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbBattleMouseExited(evt);
            }
        });
        jbBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBattleActionPerformed(evt);
            }
        });
        getContentPane().add(jbBattle);
        jbBattle.setBounds(450, 500, 120, 60);

        nameBlueTeam.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        nameBlueTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulbasaur", "Pikachu", "Gyarados", " " }));
        nameBlueTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBlueTeamActionPerformed(evt);
            }
        });
        getContentPane().add(nameBlueTeam);
        nameBlueTeam.setBounds(0, 290, 100, 30);

        nameRedTeam.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        nameRedTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulbasaur", "Pikachu", "Gyarados", " " }));
        getContentPane().add(nameRedTeam);
        nameRedTeam.setBounds(630, 290, 100, 30);
        getContentPane().add(type2);
        type2.setBounds(430, 140, 250, 160);
        getContentPane().add(type3);
        type3.setBounds(45, 140, 250, 160);

        jbChoose.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jbChoose.setText("Choose");
        jbChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChooseActionPerformed(evt);
            }
        });
        getContentPane().add(jbChoose);
        jbChoose.setBounds(320, 282, 90, 40);

        jcTypeBerry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berry", "GoldBerry", "MysteryBerry" }));
        getContentPane().add(jcTypeBerry);
        jcTypeBerry.setBounds(490, 610, 120, 22);

        jcTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue Team", "Red Team" }));
        getContentPane().add(jcTeam);
        jcTeam.setBounds(490, 650, 120, 22);

        txtExplain.setColumns(20);
        txtExplain.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        txtExplain.setRows(5);
        jScrollPane3.setViewportView(txtExplain);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 590, 320, 111);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemongame/Pokeball.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 340, 300, 380);

        description.setText("Description");
        getContentPane().add(description);
        description.setBounds(50, 640, 80, 16);

        jLabel1.setText("Type of berry");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 610, 80, 16);

        jLabel2.setText("Team");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 650, 41, 16);

        jPanel1.setBackground(new java.awt.Color(245, 171, 53));

        nameProgram.setFont(new java.awt.Font("Angsana New", 1, 50)); // NOI18N
        nameProgram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameProgram.setText("PokemonGame");
        jPanel1.add(nameProgram);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 70);

        jPanel2.setBackground(new java.awt.Color(68, 108, 179));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 350, 200);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(350, 70, 20, 250);

        jPanel5.setBackground(new java.awt.Color(46, 204, 113));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 320, 730, 410);

        jPanel6.setBackground(new java.awt.Color(1, 50, 67));

        blueTeam.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        blueTeam.setForeground(new java.awt.Color(240, 240, 240));
        blueTeam.setText("Blue Team");
        jPanel6.add(blueTeam);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 70, 350, 50);

        jPanel7.setBackground(new java.awt.Color(150, 40, 27));

        redTeam.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        redTeam.setForeground(new java.awt.Color(240, 240, 240));
        redTeam.setText("Red Team");
        jPanel7.add(redTeam);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(370, 70, 360, 50);

        jPanel4.setBackground(new java.awt.Color(192, 57, 43));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(370, 120, 360, 200);

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 750, 780);
    }// </editor-fold>//GEN-END:initComponents

    private void jbChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChooseActionPerformed
        // TODO add your handling code here:
        String typePokemon = nameBlueTeam.getSelectedItem().toString();
        String typePokemon2 = nameRedTeam.getSelectedItem().toString();
        switch(typePokemon){
            case "Bulbasaur" : 
                        type3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\bulbasaur.PNG"));
                        txtStatus1.setText(printStatus(pokemons,0));
                        break;
            case "Pikachu" : 
                        type3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\pikachu.PNG"));
                        txtStatus1.setText(printStatus(pokemons,1));
                        break;
            case "Gyarados" : 
                        type3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\gyarados.PNG"));
                        txtStatus1.setText(printStatus(pokemons,2));
                        break;
        }
        switch(typePokemon2){
            case "Bulbasaur" : 
                        type2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\bulbasaur.PNG"));
                        txtStatus2.setText(printStatus(pokemons,3));
                        break;
            case "Pikachu" : 
                        type2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\pikachu.PNG"));
                        txtStatus2.setText(printStatus(pokemons,4));
                        break;
            case "Gyarados" : 
                        type2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PAWITRA\\Desktop\\PokemonGame\\src\\pokemongame\\picpokemon\\gyarados.PNG"));
                        txtStatus2.setText(printStatus(pokemons,5));
                        break;
        }

    }//GEN-LAST:event_jbChooseActionPerformed

    private void jbFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFeedActionPerformed
        // TODO add your handling code here:
        String typeBerry = jcTypeBerry.getSelectedItem().toString();
        String team = jcTeam.getSelectedItem().toString();
        String typePokemon = nameBlueTeam.getSelectedItem().toString();
        String typePokemon2 = nameRedTeam.getSelectedItem().toString();
        switch (typeBerry) {
            case "Berry":
                if (team.equals("Blue Team")) {
                    switch (typePokemon) {
                        case "Bulbasaur":
                            pokemons.get(0).eat(new Berry(0));
                            txtStatus1.setText(printHealth(pokemons, 0));
                            break;
                        case "Pikachu":
                            pokemons.get(1).eat(new Berry(0));
                            txtStatus1.setText(printHealth(pokemons, 1));
                            break;
                        case "Gyarados":
                            pokemons.get(2).eat(new Berry(0));
                            txtStatus1.setText(printHealth(pokemons, 2));
                            break;
                    }
                }
                else if(team.equals("Red Team")){
                    switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(3).eat(new Berry(0));
                            txtStatus2.setText(printHealth(pokemons, 3));
                            break;
                        case "Pikachu":
                            pokemons.get(4).eat(new Berry(0));
                            txtStatus2.setText(printHealth(pokemons, 4));
                            break;
                        case "Gyarados":
                            pokemons.get(5).eat(new Berry(0));
                            txtStatus2.setText(printHealth(pokemons, 5));
                            break;
                    }
                }
                break;
            case "GoldBerry":
                if (team.equals("Blue Team")) {
                    switch (typePokemon) {
                        case "Bulbasaur":
                            pokemons.get(0).eat(new Berry(1));
                            txtStatus1.setText(printHealth(pokemons, 0));
                            break;
                        case "Pikachu":
                            pokemons.get(1).eat(new Berry(1));
                            txtStatus1.setText(printHealth(pokemons, 1));
                            break;
                        case "Gyarados":
                            pokemons.get(2).eat(new Berry(1));
                            txtStatus1.setText(printHealth(pokemons, 2));
                            break;
                    }
                }
                else if(team.equals("Red Team")){
                    switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(3).eat(new Berry(1));
                            txtStatus2.setText(printHealth(pokemons, 3));
                            break;
                        case "Pikachu":
                            pokemons.get(4).eat(new Berry(1));
                            txtStatus2.setText(printHealth(pokemons, 4));
                            break;
                        case "Gyarados":
                            pokemons.get(5).eat(new Berry(1));
                            txtStatus2.setText(printHealth(pokemons, 5));
                            break;
                    }
                }
                break;
            case "MysteryBerry":
                if (team.equals("Blue Team")) {
                    switch (typePokemon) {
                        case "Bulbasaur":
                            pokemons.get(0).eat(new Berry(2));
                            txtStatus1.setText(printHealth(pokemons, 0));
                            break;
                        case "Pikachu":
                            pokemons.get(1).eat(new Berry(2));
                            txtStatus1.setText(printHealth(pokemons, 1));
                            break;
                        case "Gyarados":
                            pokemons.get(2).eat(new Berry(2));
                            txtStatus1.setText(printHealth(pokemons, 2));
                            break;
                    }
                }
                else if(team.equals("Red Team")){
                    switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(3).eat(new Berry(2));
                            txtStatus2.setText(printHealth(pokemons, 3));
                            break;
                        case "Pikachu":
                            pokemons.get(4).eat(new Berry(2));
                            txtStatus2.setText(printHealth(pokemons, 4));
                            break;
                        case "Gyarados":
                            pokemons.get(5).eat(new Berry(2));
                            txtStatus2.setText(printHealth(pokemons, 5));
                            break;
                    }
                }
                break;
        }
        
        
    }//GEN-LAST:event_jbFeedActionPerformed

    private void jbFeedMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFeedMouseMoved
        // TODO add your handling code here:
        txtExplain.setText("1. เลือกฝั่งโปเกมอนที่ต้องการให้อาหาร" + "\n2. เลือกชนิดของ Berry ที่ต้องการให้" + "\n3. เริ่มการให้อาหาร");
        
    }//GEN-LAST:event_jbFeedMouseMoved

    private void jbFeedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFeedMouseExited
        // TODO add your handling code here:
        txtExplain.setText("");
    }//GEN-LAST:event_jbFeedMouseExited

    private void jbExerciseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExerciseMouseMoved
        // TODO add your handling code here:
        txtExplain.setText("1. เลือกฝั่งโปเกมอนที่ต้องการออกกำลังกาย" + "\n2. เริ่มการออกกำลังกาย");
    }//GEN-LAST:event_jbExerciseMouseMoved

    private void jbExerciseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExerciseMouseExited
        // TODO add your handling code here:
        txtExplain.setText("");
    }//GEN-LAST:event_jbExerciseMouseExited

    private void jbBattleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBattleMouseMoved
        // TODO add your handling code here:
        txtExplain.setText("1. เลือกชนิดโปเกมอนแต่ละฝั่งที่ต้องการให้ต่อสู้" + "\n2. กดปุ่ม Choose" + "\n3. เริ่มการ Battle");
    }//GEN-LAST:event_jbBattleMouseMoved

    private void jbBattleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBattleMouseExited
        // TODO add your handling code here:
        txtExplain.setText("");
    }//GEN-LAST:event_jbBattleMouseExited

    private void jbExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExerciseActionPerformed
        // TODO add your handling code here:
        String team = jcTeam.getSelectedItem().toString();
        String typePokemon = nameBlueTeam.getSelectedItem().toString();
        String typePokemon2 = nameRedTeam.getSelectedItem().toString();
                if (team.equals("Blue Team")) {
                    switch (typePokemon) {
                        case "Bulbasaur":
                            pokemons.get(0).move();
                            txtStatus1.setText(printWeight(pokemons, 0));
                            break;
                        case "Pikachu":
                            pokemons.get(1).move();
                            txtStatus1.setText(printWeight(pokemons, 1));
                            break;
                        case "Gyarados":
                            pokemons.get(2).move();
                            txtStatus1.setText(printWeight(pokemons, 2));
                            break;
                    }
                }
                else if(team.equals("Red Team")){
                    switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(3).move();
                            txtStatus2.setText(printWeight(pokemons, 3));
                            break;
                        case "Pikachu":
                            pokemons.get(4).move();
                            txtStatus2.setText(printWeight(pokemons, 4));
                            break;
                        case "Gyarados":
                            pokemons.get(5).move();
                            txtStatus2.setText(printWeight(pokemons, 5));
                            break;
                    }
                }
    }//GEN-LAST:event_jbExerciseActionPerformed

    private void jbBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBattleActionPerformed
        // TODO add your handling code here:
        String typePokemon = nameBlueTeam.getSelectedItem().toString();
        String typePokemon2 = nameRedTeam.getSelectedItem().toString();
        
        switch(typePokemon){
            case "Bulbasaur" : 
                        switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(0).attack(pokemons.get(3));
                            pokemons.get(3).attack(pokemons.get(0));
                            txtStatus1.setText(printStatus(pokemons,0));
                            txtStatus2.setText(printStatus(pokemons,3));
                            break;
                        case "Pikachu":
                            pokemons.get(0).attack(pokemons.get(4));
                            pokemons.get(4).attack(pokemons.get(0));
                            txtStatus1.setText(printStatus(pokemons,0));
                            txtStatus2.setText(printStatus(pokemons,4));
                            break;
                        case "Gyarados":
                            pokemons.get(0).attack(pokemons.get(5));
                            pokemons.get(5).attack(pokemons.get(0));
                            txtStatus1.setText(printStatus(pokemons,0));
                            txtStatus2.setText(printStatus(pokemons,5));
                            break;
                    }
                        break;
            case "Pikachu" : 
                        switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(1).attack(pokemons.get(3));
                            pokemons.get(3).attack(pokemons.get(1));
                            txtStatus1.setText(printStatus(pokemons,1));
                            txtStatus2.setText(printStatus(pokemons,3));
                            break;
                        case "Pikachu":
                            pokemons.get(1).attack(pokemons.get(4));
                            pokemons.get(4).attack(pokemons.get(1));
                            txtStatus1.setText(printStatus(pokemons,1));
                            txtStatus2.setText(printStatus(pokemons,4));
                            break;
                        case "Gyarados":
                            pokemons.get(1).attack(pokemons.get(5));
                            pokemons.get(5).attack(pokemons.get(1));
                            txtStatus1.setText(printStatus(pokemons,1));
                            txtStatus2.setText(printStatus(pokemons,5));
                            break;
                    }
                        break;
            case "Gyarados" : 
                        switch (typePokemon2) {
                        case "Bulbasaur":
                            pokemons.get(2).attack(pokemons.get(3));
                            pokemons.get(3).attack(pokemons.get(2));
                            txtStatus1.setText(printStatus(pokemons,2));
                            txtStatus2.setText(printStatus(pokemons,3));
                            break;
                        case "Pikachu":
                            pokemons.get(2).attack(pokemons.get(4));
                            pokemons.get(4).attack(pokemons.get(2));
                            txtStatus1.setText(printStatus(pokemons,2));
                            txtStatus2.setText(printStatus(pokemons,4));
                            break;
                        case "Gyarados":
                            pokemons.get(2).attack(pokemons.get(5));
                            pokemons.get(5).attack(pokemons.get(2));
                            txtStatus1.setText(printStatus(pokemons,2));
                            txtStatus2.setText(printStatus(pokemons,5));
                            break;
                    }
                        break;
        }
    }//GEN-LAST:event_jbBattleActionPerformed

    private void nameBlueTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBlueTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBlueTeamActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new java.lang.Runnable() {
            public void run() {
                new PokemonFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueTeam;
    private javax.swing.JLabel description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbBattle;
    private javax.swing.JButton jbChoose;
    private javax.swing.JButton jbExercise;
    private javax.swing.JButton jbFeed;
    private javax.swing.JComboBox<String> jcTeam;
    private javax.swing.JComboBox<String> jcTypeBerry;
    private javax.swing.JComboBox<String> nameBlueTeam;
    private javax.swing.JLabel nameProgram;
    private javax.swing.JComboBox<String> nameRedTeam;
    private javax.swing.JLabel redTeam;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JTextArea txtExplain;
    private javax.swing.JTextArea txtStatus1;
    private javax.swing.JTextArea txtStatus2;
    private javax.swing.JLabel type2;
    private javax.swing.JLabel type3;
    // End of variables declaration//GEN-END:variables
}
